apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-maintenance-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: machine-maintenance-operator
  template:
    metadata:
      labels:
        name: machine-maintenance-operator
    spec:
      serviceAccountName: machine-maintenance-operator
      containers:
        - name: machine-maintenance-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - machine-maintenance-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "machine-maintenance-operator"
